### ISSUE TITLE
Why are passwords all lowercase?

### ISSUE THREAD

**Issue by dangerfish96** [davidtavarez/pwndb#17]
Is it a bug or a feature that the passwords are all lowercase?

**Comment by davidtavarez** [comment]
bug

**Comment by davidtavarez** [comment]
Fixed here https://github.com/davidtavarez/pwndb/commit/00497aa8dde1184e9c7eb78c87a9baa97c7041d7

Update the code and try again please

**Comment by dangerfish96** [comment]
Works now
