### ISSUE TITLE
getting error message while running tool

### ISSUE THREAD

**Issue by ismailtasdelen** [davidtavarez/pwndb#2]
Hello @davidtavarez & @D4Vinci ,

Getting error message while running tool.

![screenshot at 2019-01-31 09-23-14](https://user-images.githubusercontent.com/15425071/52060367-0d1f5980-253a-11e9-92fe-2d26f1a8616f.png)

Why is this problem caused ? I'd appreciate it if you could help. I want to try this tool.

Thanks

**Comment by ismailtasdelen** [comment]
Hello @D4Vinci ,

https://davidtavarez.github.io/osint/2019/01/25/pwndb-command-line-tool-python.html --> I run the tool like this one in use.

This is your documentation error.

Example use ```python pwndb.py -u zzzz -d gmail.com``` this way but it is getting error.

Thanks for the came back :+1:

**Comment by D4Vinci** [comment]
Yeah, that's why I the wrote (old) on the tutorial link 😂.
If you took a look at the help menu as I said you would notice that the usage is different now, for example in your case use:
```
python pwndb.py --email zzzz@gmail.com
```

**Comment by davidtavarez** [comment]
I should update the `README.md`

**Comment by ismailtasdelen** [comment]
Thanks dude :smile:

**Comment by ismailtasdelen** [comment]
> I should update the `README.md`

Exactly :+1:
