### ISSUE TITLE
pwndb2am4tzkvold.onion is down again...

### ISSUE THREAD

**Issue by john123vzd** [davidtavarez/pwndb#20]
I have tried to access pwndb2am4tzkvold.onion with TOR browser and it appears to be down

**Comment by davidtavarez** [comment]
correct, is down again.

**Comment by john123vzd** [comment]
Is it possible to download the DB to my local computer?

**Comment by 40R40L** [comment]
hi @davidtavarez it would be great if you can add the  Collection#1 to the pwndb database , i can share a link. what do you think ?

**Comment by ivellios1988** [comment]
Looks like it's down again right now.

**Comment by harrylikespotatoes** [comment]
still down

**Comment by ivellios1988** [comment]
Woah, it's live!
