### ISSUE TITLE
No result returned ! 

### ISSUE THREAD

**Issue by 40R40L** [davidtavarez/pwndb#21]
Hi @davidtavarez  since yesterday the pwndb is retuning 0 results ! could you please check if there is somthing wrong in the server side ?

Thank you in advance :)

**Comment by Villelmo** [comment]
Exactly, the website http://pwndb2am4tzkvold.onion/ have this issue:
```

Warning: mysqli::__construct(): (HY000/2002): No such file or directory in /var/www/html/index.php on line 12
Connection failed: No such file or directory
```
I'm trying API/Web every the week but yesterday begin this problem from 12:00am until now.

**Comment by Villelmo** [comment]
Hi @davidtavarez

**Comment by davidtavarez** [comment]
I guess we all just need to wait :)

**Comment by Villelmo** [comment]
Why the website always down?. @davidtavarez

**Comment by Villelmo** [comment]
How much time the problem is solved?.

**Comment by Villelmo** [comment]
If the problem is always, why don't move the website other hosting out from deepweb?

**Comment by 40R40L** [comment]
Everything works fine !! Thanks you @davidtavarez  :)
