### ISSUE TITLE
Domain search results capped at 2001

### ISSUE THREAD

**Issue by p4lsec** [davidtavarez/pwndb#26]
When I search for a domain that has many results (for example, google.com), the results are always capped out at 2001 results. I am assuming this is a database limitation. Any ideas for a good work around?

**Comment by 0x0is1** [comment]
@p4lsec 
> When I search for a domain that has many results (for example, google.com), the results are always capped out at 2001 results. I am assuming this is a database limitation. Any ideas for a good work around?

Yeah probably it is. but this dev tool is nothing to do about the domain and their db. This tool is just for scraping from that website. 

@davidtavarez do not own the domain.

**Comment by davidtavarez** [comment]
thanks @0x0is1 👍
