### ISSUE TITLE
Service is down

### ISSUE THREAD

**Issue by osiris2600** [davidtavarez/pwndb#27]
Hi,

Will the service be back up any time soon?

Thanks

**Comment by 5l1v3r1** [comment]
Service is down again. Is there any mirrors ?

**Comment by 0x0is1** [comment]
Service is down but domain is still working.
A non-onion mirror site here : 

`http://pwndb2am4tzkvold.onion.pet/`

**Comment by 226914011** [comment]
Domain is no longer working
Any new mirrors?

**Comment by 0x0is1** [comment]
@226914011 
`http://pwndb2am4tzkvold.onion.pet/`
The above mentioned site is working quite well without tor. You can try with any simple emails or passwords if want to check it. If your creds is not showing up in there, that mean your creds are not in leaked database.
