### ISSUE TITLE
bash: virtualenv: command not found

### ISSUE THREAD

**Issue by kali64amd** [davidtavarez/pwndb#28]
hi there,

Could anyone please help me in this error ??

root@Shinobi:~# cd Desktop/Tool
root@Shinobi:~/Desktop/Tool# git clone https://github.com/davidtavarez/pwndb
Cloning into 'pwndb'...
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 142 (delta 0), reused 0 (delta 0), pack-reused 138
Receiving objects: 100% (142/142), 36.95 KiB | 147.00 KiB/s, done.
Resolving deltas: 100% (61/61), done.
root@Shinobi:~/Desktop/Tool# cd pwndb
root@Shinobi:~/Desktop/Tool/pwndb# virtualenv venv
**bash: virtualenv: command not found**

Appreciate your help.

**Comment by 0x0is1** [comment]
Probably virtualenv is not installed on your system. Try this:
`sudo pip3 install virtualenv`
After that:
`virtualenv venv`

**Comment by kali64amd** [comment]
@

> Probably virtualenv is not installed on your system. Try this:
> `sudo pip3 install virtualenv`
> After that:
> `virtualenv venv`

Thanks for your help!!

It's Fix now. Appreciate your help.

**Comment by avinash5678** [comment]
> Probably virtualenv is not installed on your system. Try this:
> `sudo pip3 install virtualenv`
> After that:
> `virtualenv venv`

still Iam getting the error

$ sudo pip3 install virtualenv
$ virtualenv venv
virtualenv: command not found

**Comment by 0x0is1** [comment]
> > Probably virtualenv is not installed on your system. Try this:
> > `sudo pip3 install virtualenv`
> > After that:
> > `virtualenv venv`
> 
> still Iam getting the error
> 
> $ sudo pip3 install virtualenv
> $ virtualenv venv
> virtualenv: command not found

@avinash5678 
You haven't provided proper output i guess, but still i advice you to try 

`python -m pip install --user virtualenv`

Let me know if it's working for you.
