### ISSUE TITLE
[!] Can't connect to service! restart tor service and try again.

### ISSUE THREAD

**Issue by AdrianDucao** [davidtavarez/pwndb#29]
i just followed the instruction for installation however i got this message when trying to search and target my own email just to see if it's working.

**Comment by daniladyabin** [comment]
same

**Comment by ApooU2** [comment]
Open new TERMINAL window and type in tor
leave that and then rerun the pwndb command in a fresh terminal

**Comment by ApooU2** [comment]
> i just followed the instruction for installation however i got this message when trying to search and target my own email just to see if it's working.

follow my instructions

**Comment by AdrianDucao** [comment]
Sorry wasn't able to get back to you, i was able to fix it my self so it's ok. Thank you though.

**Comment by rajeshpatil015** [comment]
After installing tor it worked (##apt install tor)

**Comment by kappo25** [comment]
Hey i have the same problem but i can't find out how to solve it, how did you do?
i tried with tor but is keeping saying that it can't connect

thanks
