### ISSUE TITLE
it doesnt work ! please help me !!

### ISSUE THREAD

**Issue by kalilinusshs** [davidtavarez/pwndb#33]
when testing an email it says donate@btc.thx !!!
now what is this ? please help me to overcome this issue so that I can check leaked email credentials !
please reply

**Comment by davidtavarez** [comment]
overcome this issue? that's not an issue? you can ignore that line or just donate?
![Screen Shot 2020-05-03 at 12 02 36 PM](https://user-images.githubusercontent.com/337107/80911344-016ea400-8d36-11ea-98a8-9160e828ec50.png)
