### ISSUE TITLE
[!] Missing dependencies for SOCKS support

### ISSUE THREAD

**Issue by Krip4us** [davidtavarez/pwndb#50]
what did means?

**Comment by aakall** [comment]
Try: pip install pysocks

**Comment by therealOri** [comment]
> Try: pip install pysocks

Already installed, still same issue.

**Comment by therealOri** [comment]
[[SOLVED]]


This error message can be fixed by doing the following commands.
```bash
pip uninstall pysocks
pip install -U pysocks
```

Issue was it being an older version of pysocks.
~~This worked for me so I thought i'd share~~
