### ISSUE TITLE
Error detected

### ISSUE THREAD

**Issue by XavCC** [davidtavarez/pwndb#7]
While running standard starter

```
--> python pwndb.py -h
  File "pwndb.py", line 71
    leak = leak.lower()
                      ^
TabError: inconsistent use of tabs and spaces in indentation
```

Otherwise according PEP 8 = line (`|x|` = code line ref) : 
+ | 9 | line too long (91 > 79 characters)
+ | 12 | line too long (105 > 79 characters)
+ | 43 | line too long (107 > 79 characters)
+ | 56 | line too long (91 > 79 characters)
+ | 58 |  line too long (83 > 79 characters)
+ | 82 | line too long (105 > 79 characters)
+ | 99 | line too long (89 > 79 characters)

Should I have to work on it onto a PullRequest ?

**Comment by davidtavarez** [comment]
it would be great! :+1:

**Comment by davidtavarez** [comment]
Changes included in this commit: https://github.com/davidtavarez/pwndb/commit/988f3e3157eeca4a9126b0e99223623ce90ca185
