### ISSUE TITLE
License

### ISSUE THREAD

**Issue by XavCC** [davidtavarez/pwndb#9]
It would be great with FLOSS license.
What do you think about that ?

**Comment by davidtavarez** [comment]
Which one do you recommend and why?

**Comment by davidtavarez** [comment]
Interesting... I guess I'm going to choose MIT. Thanks!

**Comment by davidtavarez** [comment]
Updated the README file https://github.com/davidtavarez/pwndb/blob/master/README.md

**Comment by XavCC** [comment]
With a `LICENSE.txt` or `LICENSE.md` onto the repositiry with your name ? It will be fine :wink:

**Comment by davidtavarez** [comment]
https://github.com/davidtavarez/pwndb/blob/master/LICENSE.txt
